version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mlp10_db
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "${DB_PORT}:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/1433"]
      interval: 10s
      timeout: 5s
      retries: 30

  mlp10:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlp10_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${APP_PORT}:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${DEFAULT_CONNECTION}
    env_file:
      - .env
    restart: unless-stopped

volumes:
  sqlserverdata:
