name: CI Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Job 1: Проверка качества Dockerfile
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error
          output-file: hadolint-report.txt

      - name: Upload Hadolint report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: hadolint-report
          path: hadolint-report.txt

  # Job 2: Run .NET Tests
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: "**/TestResults/*.trx"

  # Job 3: Build Docker image (only if lint and tests pass)
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t myapp:test .
          echo "Docker image built successfully!"

      - name: Save build log
        run: |
          echo "Build completed at $(date)" > build-log.txt
          docker images | grep myapp >> build-log.txt

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build-log.txt

  # Job 4: Docker Compose Test (Optional - tests the full stack)
  integration-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Create .env file for testing
        run: |
          cat > .env << EOF
          SA_PASSWORD=YourStrong@Passw0rd
          DB_PORT=1433
          APP_PORT=8080
          ASPNETCORE_ENVIRONMENT=Development
          DEFAULT_CONNECTION=Server=db;Database=master;User=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;
          EOF

      - name: Build and test with Docker Compose
        run: |
          docker-compose up --build -d
          sleep 30  # Wait for services to start
          docker-compose ps
          # Test if web service is responding
          curl -f http://localhost:8080 || echo "Service not ready yet"
          docker-compose down

      - name: Save integration test log
        run: |
          echo "Integration test completed at $(date)" > integration-log.txt
          docker-compose logs --no-color > docker-compose-logs.txt

      - name: Upload integration logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-logs
          path: |
            integration-log.txt
            docker-compose-logs.txt