name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '9.0.x' # Use the .NET 9 SDK

jobs:
  build-and-test:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    # Optional: Run tests on multiple operating systems
    strategy:
      matrix:
        os: [ubuntu-latest] # You can also add windows-latest, macOS-latest

    steps:
      # Step 1: Check out your code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Step 3: Restore project dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the project
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # Step 5: Run the tests
      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal
